name = "interviews-api"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "interviews_db"
database_id = "ca1cba03-9281-4bab-ac79-0ae16b39b88a"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "files"
preview_bucket_name = "preview-files"
